### ISSUE TITLE
Inspect brouter code - defining polygons

### ISSUE THREAD

**Issue by Nieminik** [CAN-Group/can#3]

**Comment by Yamsha75** [comment]
Maybe this will help:
https://github.com/abrensch/brouter/pull/97

**Comment by Yamsha75** [comment]
I found this:

https://brouter.de/brouter-web/#map=17/45.75882/4.89995/standard&lonlats=4.899709,45.756715;4.90104,45.760248&polygons=4.897735,45.75655,4.89943,45.75655,4.89943,45.75929,4.897735,45.75929

Will try it in self-hosted brouter app and say if it worked.

**Comment by Yamsha75** [comment]
If we use Flask backend as a proxy to brouter, we can store static county geometries in Flask, avoiding the need to modify brouter at all. The request from frontend would use county IDs and the request from Flask to brouter would use polygons.

**Comment by Yamsha75** [comment]
We will proceed with Flask as proxy to brouter as stated above.
