### ISSUE TITLE
Investigate frontend ReactJS app environment

### ISSUE THREAD

**Issue by Yamsha75** [CAN-Group/can#4]
Investigate how should our ReactJS frontend be packaged:
- as a separate app in Node.js, or
- embedded in Flask backend

First option will be easier for development and probably require less configuration.
Second option will not require [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) between those two modules.

**Comment by Tamasa94** [comment]
Separate App will be the best solution for our application with Node.JS
