### ISSUE TITLE
Make the interactive slider work

### ISSUE THREAD

**Issue by Yamsha75** [CAN-Group/can#41]
Please investigate refreshing counties state to make the slider work as intended. If possible, add labels below the slider indicating current choice of percentage of red/yellow/green zones

**Comment by Tamasa94** [comment]
almost done, i need to repair a small issue on trigering event. it renderers previous geojson state

**Comment by Tamasa94** [comment]
slider has been repaired in last commit

**Comment by Yamsha75** [comment]
Implemented and merged in #52
