### ISSUE TITLE
Send two routing requests to backend

### ISSUE THREAD

**Issue by Yamsha75** [CAN-Group/can#42]
Frontend should send two routing requests to backend and display both in different colours:
- first with no counties to skip
- second using current choice of counties to skip

If it is possible, send both immediately, but if it's not possible, I think sending the first request with no counties to skip would give better feedback to the user as the response would be quicker.

Maybe add a text above the route to indicate if it is "safe" or "dangerous", or a description somewhere that would explain colours of the paths.

A thing to think through: what should we do if both paths are equal (no going around red zones)?

**Comment by Yamsha75** [comment]
A bug in brouter has turned up while implementing this feature. Bugfix commited to [CAN-Group/brouter](https://github.com/CAN-Group/brouter) in [e49b491](https://github.com/CAN-Group/brouter/commit/e49b4919fed54cae3893da81bfb27bf051e857e7) and (will be) merged here in #50

**Comment by Tamasa94** [comment]
done on frontend_features
