### ISSUE TITLE
Choose a few routing profiles and give them friendly names

### ISSUE THREAD

**Issue by Yamsha75** [CAN-Group/can#43]
Please choose a few routing profiles from [the list](https://github.com/CAN-Group/can/blob/master/flask-app/static/routing_profiles.json) to narrow the choice for user - the list is too long and confusing right now - and give those some translated friendly names in the interface.

I suggest the following, but feel free to do it your way
- car-eco (least fuel consumption)
- car-short (least distance)
- car-fast (least time)
- car-fast-nominorroads (least time + avoid minor roads)

**Comment by Yamsha75** [comment]
We will change `static/routing_profiles.json` in flask-app from a list to a dict mapping profile names to friendly names. I'll handle the backend part

**Comment by Ersgen** [comment]
#55 - Dictionary format needed to be change to fit into JS formating

**Comment by Ersgen** [comment]
Implemented.
