### ISSUE TITLE
Add using environment variables for setting backend address and port in frontend

### ISSUE THREAD

**Issue by Yamsha75** [CAN-Group/can#46]
For purposes of dockerizing the frontend we need to be able to set backend host and port in [connection.js](https://github.com/CAN-Group/can/blob/master/can-frontend/src/components/helpers/js/connection.js) (or preferably a single backend url) using environment variables - `BACKEND_URL`, or `BACKEND_HOST` + `BACKEND_PORT`. Please set default url to `http://localhost:5000`

You can follow [this tutorial](https://www.twilio.com/blog/working-with-environment-variables-in-node-js-html)

**Comment by Nieminik** [comment]
Added in #62

**Comment by Yamsha75** [comment]
Merged in #62
